apiVersion: v1
kind: Pod
metadata:
  name: volume-pod

spec:
  containers:
  - name: nginx-container
    image: nginx

    volumeMounts:
    - mountPath: /data
      name: my-storage

  volumes:
  - name: my-storage
    hostPath:
      path: /tmp/data
      type: DirectoryOrCreate